Test fix

diff --git a/.jenkins/Jenkinsfile b/.jenkins/Jenkinsfile
--- a/.jenkins/Jenkinsfile
+++ b/.jenkins/Jenkinsfile
@@ -203,7 +203,7 @@ pipeline {
               }
             }
             steps {
-              _test("test", [current: 2, all: 40])
+              _testAxisTest("test", env.arch, env.jdk, "2/40")
             }
           }
         stage('test-compression_1/10') {
@@ -479,6 +479,59 @@ def getNodeArch(arch) {
       return "cassandra-arm64"
     default:
       error("Unsupported architecture '${arch}'")
+  }
+}
+
+def _testAxisTest(".build/docker/run-tests.sh", test_type, arch, jdk, python="3.7", cython="no", split) {
+  echo "Spawning ${STAGE_NAME} `${test_script} ${test_type} ${split} ${jdk}` with arch=${arch} jdk=${jdk} python${python} cython=${cython}"
+  node(_getNodeArch(arch)) {
+    branchName: "${STAGE_NAME} ${test_script} ${test_type} ${split} ${jdk} ${NODE_NAME}"
+    echo "Starting ${STAGE_NAME} `${test_script} ${test_type} ${split} ${jdk}` with arch=${arch} jdk=${jdk} python${python} cython=${cython} on ${NODE_NAME}"
+    checkout scm
+    sh "mkdir -p build"
+    def build_dir = sh( returnStdout: true, script:"mktemp -d ${WORKSPACE}/build/build_docker_run.XXXXXXXXXX" ).trim()
+    def build_dir_rel = build_dir - "${WORKSPACE}/"
+
+    def cassandra_dtest_dir = "${build_dir}/cassandra-dtest"
+    if (STAGE_NAME.startsWith("dtest")) {
+        def dtestRepo = "https://github.com/apache/cassandra-dtest"
+        def dtestBranch =  "trunk"
+        sh "until git clone --quiet --depth 1 -b ${dtestBranch} ${dtestRepo} \"${cassandra_dtest_dir}\" ; do echo \"git cloning cassandra-dtest failed… trying again… \" ; done"
+    }
+
+    def statusCode = 0, attempt = 1
+    retry(2) {
+      if (attempt > 1) { sleep(60 * attempt) }
+      def logfile = "${JOB_NAME}_${BUILD_NUMBER}_${test_type}_jdk${jdk}_python_${python}_${cython}_${arch}_attempt_${attempt}.log"
+      try {
+        dir("${build_dir}") {
+          unstash name: "${arch}_${jdk}"
+        }
+        echo "Executing ${STAGE_NAME} `${test_script} ${test_type} ${split} ${jdk} 2>&1 | tee ${build_dir}/${logfile}` on ${NODE_NAME} with jdk=${jdk} python=${python} cython=${cython}"
+        statusCode = sh returnStatus:true, script:"python_version=\"${python}\" cython=\"${cython}\" build_dir=\"${build_dir}\" cassandra_dtest_dir=\"${cassandra_dtest_dir}\" ${test_script} ${test_type} ${split} ${jdk} 2>&1 | tee ${build_dir}/${logfile}"
+      } finally {
+        dir("${build_dir_rel}") {
+            if (0 == statusCode) {
+                junit testResults: "test/output/**/TEST*.xml,test/output/cqlshlib.xml,test/output/nosetests.xml", testDataPublishers: [[$class: 'StabilityTestDataPublisher']]
+                sh "xz -f test/output/**/TEST*.xml || true ; xz -f test/output/cqlshlib.xml test/output/nosetests.xml || true"
+            }
+            archiveArtifacts artifacts: "**/*_attempt_*.log.xz,test/logs/**,test/output/**/TEST*.xml.xz,test/output/cqlshlib.xml.xz,test/output/nosetests.xml.xz", fingerprint: true
+            copyToNightlies("*_attempt_*.log.xz,test/logs/**", "${test_type}/${arch}/jdk${jdk}/python${python}/cython_${cython}/" + "split_${split}".replace("/", "_"))
+        }
+        sh "rm -rf \"${build_dir}\""
+        cleanAgent(test_script)
+        if (0 != statusCode) {
+          currentBuild.result = 'FAILURE'
+          error("FAILED ${STAGE_NAME} `${test_script} ${test_type} ${split} ${jdk}` with arch=${arch} jdk=${jdk} python=${python} cython=${cython} on ${NODE_NAME}")
+        } else {
+          echo "Completed ${STAGE_NAME} `${test_script} ${test_type} ${split} ${jdk}` with arch=${arch} jdk=${jdk} python=${python} cython=${cython} on ${NODE_NAME}"
+        }
+      }
+    }
+
+    if (currentBuild.result != 'SUCCESS') unstable("${STAGE_NAME} failures (arch=${arch} jdk=${jdk} python=${python} cython=${cython} on ${NODE_NAME})")
+    if (currentBuild.result == 'ABORTED' && currentBuild.result != 'FAILURE') currentBuild.result='ABORTED'
+    if (currentBuild.result == 'FAILURE') currentBuild.result='FAILURE'
   }
 }
 
