More logs

diff --git a/.jenkins/Jenkinsfile b/.jenkins/Jenkinsfile
--- a/.jenkins/Jenkinsfile
+++ b/.jenkins/Jenkinsfile
@@ -161,11 +161,11 @@ pipeline {
               _build("build-redhat.sh rpm", "*.rpm")
             }
           }
-          // stage('fqltool-test') {
-          //   steps {
-          //     testJob("fqltool-test")
-          //   }
-          // }
+          stage('fqltool-test') {
+            steps {
+              _test("fqltool-test")
+            }
+          }
         }
       }
     }
@@ -252,7 +252,7 @@ pipeline {
     //     }
     //     stage('jvm-dtest') {
     //       steps {
-    //         testJob("jvm-dtest", 8)
+    //         _dtest("jvm-dtest", 8)
     //       }
     //     }
     //     stage('jvm-dtest-upgrade') {
@@ -339,75 +339,60 @@ def isJdkEnabled(jdk) {
  * Renders build script into pipeline steps
  **/
 def _build(build_script, toCopy="") {
-  node(getNodeArch(arch)) {
-    ws("workspace/${JOB_NAME}/${BUILD_NUMBER}/${STAGE_NAME}/${arch}/jdk-${jdk}/${env.phase}") {
-        build_script = ".build/docker/${build_script}"
-        logfile = "${JOB_NAME}_${BUILD_NUMBER}_${STAGE_NAME}_jdk${jdk}_${arch}.log"
+    build_script = ".build/docker/${build_script}"
+    logfile = "${JOB_NAME}_${BUILD_NUMBER}_${STAGE_NAME}_jdk${jdk}_${arch}.log"
+    node(getNodeArch(arch)) {
+        ws("workspace/${JOB_NAME}/${BUILD_NUMBER}/${STAGE_NAME}/${arch}/jdk-${jdk}/${env.phase}") {
+            cleanWs(disableDeferredWipeout: true)
+            fetchSource(STAGE_NAME, arch, jdk)
 
-        cleanWs(disableDeferredWipeout: true)
-        fetchSource(STAGE_NAME, arch, jdk)
-
-        catchError(buildResult: null, message: 'shit happens', stageResult: 'FAILURE') {
-            sh script:"build_dir='${WORKSPACE}/build' ${build_script} ${jdk} > ${logfile} 2>&1"
-            if ("jar" == STAGE_NAME) { // only stash the project built files. all dependency libraries are restored from the local maven repo using `ant resolver-dist-lib`
-                stash name: "${arch}_${jdk}", useDefaultExcludes: false //, includes: '**/*.jar' //, includes: "*.jar,classes/**,test/classes/**,tools/**"
+            catchError(buildResult: null, message: 'shit happens', stageResult: 'FAILURE') {
+                sh script:"build_dir='${WORKSPACE}/build' ${build_script} ${jdk} > ${logfile} 2>&1"
+                if ("jar" == STAGE_NAME) { // only stash the project built files. all dependency libraries are restored from the local maven repo using `ant resolver-dist-lib`
+                    stash name: "${arch}_${jdk}", useDefaultExcludes: false //, includes: '**/*.jar' //, includes: "*.jar,classes/**,test/classes/**,tools/**"
+                }
+                copyToNightlies("${toCopy}", "${STAGE_NAME}/jdk${jdk}/${arch}/")
             }
-            copyToNightlies("${toCopy}", "${STAGE_NAME}/jdk${jdk}/${arch}/")
-        }
 
-        sh "xz -f *.log"
-        archiveArtifacts artifacts: "**/*.log.xz", fingerprint: true
-        copyToNightlies("**/*.log.xz", "${STAGE_NAME}/jdk${jdk}/${arch}/")
-        cleanAgent(build_script)
+            sh "cat ${logfile}"
+            sh "xz -f *.log"
+            archiveArtifacts artifacts: "**/*.log.xz", fingerprint: true
+            copyToNightlies("**/*.log.xz", "${STAGE_NAME}/jdk${jdk}/${arch}/")
+            cleanAgent(build_script)
+        }
     }
-  }
 }
 
-def _test(test_script, test_type, arch, jdk, python, cython, split) {
-  echo "Spawning ${STAGE_NAME} `${test_script} ${test_type} ${split} ${jdk}` with arch=${arch} jdk=${jdk} python${python} cython=${cython}"
-  node(_getNodeArch(arch)) {
-    branchName: "${STAGE_NAME} ${test_script} ${test_type} ${split} ${jdk} ${NODE_NAME}"
-    echo "Starting ${STAGE_NAME} `${test_script} ${test_type} ${split} ${jdk}` with arch=${arch} jdk=${jdk} python${python} cython=${cython} on ${NODE_NAME}"
-    checkout scm
-    sh "mkdir -p build"
-    def build_dir = sh( returnStdout: true, script:"mktemp -d ${WORKSPACE}/build/build_docker_run.XXXXXXXXXX" ).trim()
-    def build_dir_rel = build_dir - "${WORKSPACE}/"
+def _test(test_script, test_type) { //, arch, jdk, python, cython, split) {
+  node(getNodeArch(arch)) {
+    ws("workspace/${JOB_NAME}/${BUILD_NUMBER}/${STAGE_NAME}/${arch}/jdk-${jdk}/${env.phase}") {
+        fetchSource(STAGE_NAME, arch, jdk)
 
-    def cassandra_dtest_dir = "${build_dir}/cassandra-dtest"
-    if (STAGE_NAME.startsWith("dtest")) {
-        def dtestRepo = "https://github.com/apache/cassandra-dtest"
-        def dtestBranch =  "trunk"
-        sh "until git clone --quiet --depth 1 -b ${dtestBranch} ${dtestRepo} \"${cassandra_dtest_dir}\" ; do echo \"git cloning cassandra-dtest failed… trying again… \" ; done"
-    }
-
-    def statusCode = 0, attempt = 1
-    retry(2) {
-      if (attempt > 1) { sleep(60 * attempt) }
-      def logfile = "${JOB_NAME}_${BUILD_NUMBER}_${test_type}_jdk${jdk}_python_${python}_${cython}_${arch}_attempt_${attempt}.log"
-      try {
-        dir("${build_dir}") {
-          unstash name: "${arch}_${jdk}"
-        }
-        echo "Executing ${STAGE_NAME} `${test_script} ${test_type} ${split} ${jdk} 2>&1 | tee ${build_dir}/${logfile}` on ${NODE_NAME} with jdk=${jdk} python=${python} cython=${cython}"
-        statusCode = sh returnStatus:true, script:"python_version=\"${python}\" cython=\"${cython}\" build_dir=\"${build_dir}\" cassandra_dtest_dir=\"${cassandra_dtest_dir}\" ${test_script} ${test_type} ${split} ${jdk} 2>&1 | tee ${build_dir}/${logfile}"
-      } finally {
-        dir("${build_dir_rel}") {
-            if (0 == statusCode) {
-                junit testResults: "test/output/**/TEST*.xml,test/output/cqlshlib.xml,test/output/nosetests.xml", testDataPublishers: [[$class: 'StabilityTestDataPublisher']]
-                sh "xz -f test/output/**/TEST*.xml || true ; xz -f test/output/cqlshlib.xml test/output/nosetests.xml || true"
+        def logfile = "${JOB_NAME}_${BUILD_NUMBER}_${test_type}_jdk${jdk}_python_${python}_${cython}_${arch}_attempt_${attempt}.log"
+        try {
+            dir("${build_dir}") {
+            unstash name: "${arch}_${jdk}"
             }
-            archiveArtifacts artifacts: "**/*_attempt_*.log.xz,test/logs/**,test/output/**/TEST*.xml.xz,test/output/cqlshlib.xml.xz,test/output/nosetests.xml.xz", fingerprint: true
-            copyToNightlies("*_attempt_*.log.xz,test/logs/**", "${test_type}/${arch}/jdk${jdk}/python${python}/cython_${cython}/" + "split_${split}".replace("/", "_"))
+            echo "Executing ${STAGE_NAME} `${test_script} ${test_type} ${split} ${jdk} 2>&1 | tee ${build_dir}/${logfile}` on ${NODE_NAME} with jdk=${jdk} python=${python} cython=${cython}"
+            statusCode = sh returnStatus:true, script:"python_version=\"${python}\" cython=\"${cython}\" build_dir=\"${build_dir}\" ${test_script} ${test_type} ${split} ${jdk} 2>&1 | tee ${build_dir}/${logfile}"
+        } finally {
+            dir("${build_dir_rel}") {
+                if (0 == statusCode) {
+                    junit testResults: "test/output/**/TEST*.xml,test/output/cqlshlib.xml,test/output/nosetests.xml", testDataPublishers: [[$class: 'StabilityTestDataPublisher']]
+                    sh "xz -f test/output/**/TEST*.xml || true ; xz -f test/output/cqlshlib.xml test/output/nosetests.xml || true"
+                }
+                archiveArtifacts artifacts: "**/*_attempt_*.log.xz,test/logs/**,test/output/**/TEST*.xml.xz,test/output/cqlshlib.xml.xz,test/output/nosetests.xml.xz", fingerprint: true
+                copyToNightlies("*_attempt_*.log.xz,test/logs/**", "${test_type}/${arch}/jdk${jdk}/python${python}/cython_${cython}/" + "split_${split}".replace("/", "_"))
+            }
+            sh "rm -rf \"${build_dir}\""
+            cleanAgent(test_script)
+            if (0 != statusCode) {
+            currentBuild.result = 'FAILURE'
+            error("FAILED ${STAGE_NAME} `${test_script} ${test_type} ${split} ${jdk}` with arch=${arch} jdk=${jdk} python=${python} cython=${cython} on ${NODE_NAME}")
+            } else {
+            echo "Completed ${STAGE_NAME} `${test_script} ${test_type} ${split} ${jdk}` with arch=${arch} jdk=${jdk} python=${python} cython=${cython} on ${NODE_NAME}"
+            }
         }
-        sh "rm -rf \"${build_dir}\""
-        cleanAgent(test_script)
-        if (0 != statusCode) {
-          currentBuild.result = 'FAILURE'
-          error("FAILED ${STAGE_NAME} `${test_script} ${test_type} ${split} ${jdk}` with arch=${arch} jdk=${jdk} python=${python} cython=${cython} on ${NODE_NAME}")
-        } else {
-          echo "Completed ${STAGE_NAME} `${test_script} ${test_type} ${split} ${jdk}` with arch=${arch} jdk=${jdk} python=${python} cython=${cython} on ${NODE_NAME}"
-        }
-      }
     }
 
     if (currentBuild.result != 'SUCCESS') unstable("${STAGE_NAME} failures (arch=${arch} jdk=${jdk} python=${python} cython=${cython} on ${NODE_NAME})")
